version: '3.9'

services:
  pm2_api:
    build:
      context: .
      dockerfile: Dockerfile_PM2
    volumes:
      - ./dist:/usr/dist
      - ./src/public:/usr/dist/public
    ports:
      - '5000:5000'
    expose:
      - 5000
    environment:
      HOST: '0.0.0.0'
      PORT: 5000
    mem_limit: 512m
